### ISSUE TITLE
Proposal: Add concept of "events" to pipeline execution criteria

### ISSUE THREAD

**Issue by krancour** [lovethedrake/prototype#28]
# Status Quo

Currently, the method of describing criteria for pipeline execution is a little bit clunky.

Take this, for example:

```
pipelines:
  test:
    criteria:
      branches:
        ignore:
        - master
```

What this _says_ is that this pipeline should execute any time the "branch" isn't `master`, but it isn't very clear in communicating my actual intent and may select some conditions I didn't intend. My intent, in this case, was to execute for all all pull requests. This works, because in the event of a pull request, the custom Brigade worker considers the source branch to be the empty string and `"" != "master"`. But there are two problems here:

1. I needed to _know_ something esoteric about the worker's behavior-- namely that it considers the source branch of pull requests to be the empty string. It wouldn't have been outrageous, for instance, to assume that the worker would consider the _target_ branch of a pull request as the "branch" in question, in which case, one would look at these criteria and wonder why this pipelines _does_ execute for pull requests.
2. This will _also_ execute on _pushes_ to any branch that isn't master. That may not be a bad thing _fi that is what you want_, but in this case, it isn't actually what I wanted.

A second example:

```
pipelines:
  master:
    criteria:
      branches:
        only:
        - master
```

Here, the `master` pipeline runs for pushes to the `master` branch. But it doesn't run when a new tag is applied to the master branch. This _was_ my intended behavior, but why does it work this way? Because if the Brigade worker has a ref / tag, it only considers that tag in selecting pipelines for execution. The branch doesn't factor into the selection process at all. Again-- this is some esoteric system behavior one needs to be aware of to be successful.

# Proposal

If we introduce the concept of events, we can be unambiguous about the criteria for pipeline execution.

For example:

```
pipelines:
  test:
    criteria:
      events:
        pullRequest:
          targetBranches:
            only:
            - master
            - /feature\/.*/
```

This unambiguously says it should execute when triggered by pull requests targeted at the `master` branch or any feature branch.

```
pipelines:
  master-or-feature:
    criteria:
      events:
        push:
          branches:
            only:
            - master
            - /feature\/.*/
```

This unambiguously says it should execute when triggered by pushes to the `master` branch or any feature branch.

```
pipelines:
  release:
    criteria:
      events:
        tag:
          tags:
            only:
            - /v[0-9]+(\.[0-9]+)*(\-.+)?/
```

This unambiguously says it should execute when triggered by the application of a new semver tag.
